### ISSUE TITLE
Processing non RGB888 images

### ISSUE THREAD

**Issue by darwinjob** [darwinjob/pyramidio-bioformats#13]
The original pyramidio scaling algorithm is (presumably) the source of the several issues:
https://github.com/darwinjob/pyramidio-bioformats/issues/2
https://github.com/darwinjob/pyramidio-bioformats/issues/1

Can be fixed by either converting the input to RGB888 on a fly or by improving the scaling algorithm in here:
https://github.com/darwinjob/pyramidio-bioformats/blob/master/pyramidio/src/main/java/gov/nist/isg/pyramidio/tools/ImageResizingHelper.java

**Comment by darwinjob** [comment]
1.1.6: added -rgb parameter to convert the input to RGB888 on a fly. This is a workaround. The original pyramidio is trying to keep the tiles format identical to the input image format (which is probably a good idea).
Closing for now. See https://github.com/darwinjob/pyramidio-bioformats/issues/14

**Comment by PolarBean** [comment]
nice job! any rough estimate of how much overhead this conversion adds? just curious

**Comment by darwinjob** [comment]
Not really noticeable here on my Mac. Maybe if you use really large tiles .. maybe then it will cause some memory related issues and a performance drop as the consequence. But no one uses large tiles.

**Comment by PolarBean** [comment]
great solution!
