### ISSUE TITLE
Possible to run multithreaded?

### ISSUE THREAD

**Issue by PolarBean** [darwinjob/pyramidio-bioformats#9]
Is it possible to run the DZI converter multithreaded on a single image?

**Comment by darwinjob** [comment]
It is already multithreaded  🤓 See "parallelism" on the main page.

From the command line:
<pre>
usage: pyramidio
 -h,--help                      Display this help message and exit.
 -i,--input <arg>               Input image to convert to dzi.
 -icr,--inputCacheRatio <arg>   Ratio of the input image which can be kept
                                in cache at any time. By default, the
                                entire input image is kept in cache (value
                                1). This is the fastest but consume more
                                memory. Set to 0 to disable the cache
                                (will be slow especially with compressed
                                images such as jpg and png).
 -o,--output <arg>              Output folder or file where the output
                                will be generated.
 -p,--parallelism <arg>         Number of threads to use (default to
                                number of cpu cores).
 -tf,--tileFormat <arg>         Tile format such as jpg, png (default to
                                the same format than the input)
 -to,--tileOverlap <arg>        Tile overlap (default 1).
 -ts,--tileSize <arg>           Tile size (default 254).
</pre>

**Comment by PolarBean** [comment]
Thank you!
